version: '3'
services:
  zoo:
    image: wurstmeister/zookeeper
    hostname: zoo
    ports:
      - "2181:2181"
    expose:
      - "2118"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo:2888:3888

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: "100"
      KAFKA_NUM_PARTITIONS: "1"
      KAFKA_LISTENERS: INTERNAL://kafka:9090,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9090,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    expose:
      - "9092"
    depends_on:
      - zoo

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    image: payment
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  payment_cancelation:
    build:
      context: ./payment_cancelation
      dockerfile: Dockerfile
    image: payment_cancelation
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  payment_processing:
    build:
      context: ./payment_processing
      dockerfile: Dockerfile
    image: payment_processing
    ports:
      - "8082:8082"
    depends_on:
      - kafka

  payment_storage:
    build:
      context: ./payment_storage
      dockerfile: Dockerfile
    image: payment_storage
    depends_on:
      - kafka
      - payment_processing